// villes_seed.js — Liste prioritaire des communes reliées à Paris (<1h) via RER/Transilien (hors 93)

export const VILLES = [
  {"ville":"Juvisy-sur-Orge","cp":"91260","departement":"Essonne (91)","lignes":"RER C","terminus":"Invalides","tmin":20,"tmax":30,"gare":"Oui","lt1h":true,"prixm2":3400,"loyerm2":19},
  {"ville":"Savigny-sur-Orge","cp":"91600","departement":"Essonne (91)","lignes":"RER C","terminus":"Invalides","tmin":25,"tmax":35,"gare":"Oui","lt1h":true,"prixm2":3200,"loyerm2":19},
  {"ville":"Épinay-sur-Orge","cp":"91360","departement":"Essonne (91)","lignes":"RER C","terminus":"Invalides","tmin":25,"tmax":35,"gare":"Oui","lt1h":true,"prixm2":3100,"loyerm2":19},
  {"ville":"Ablon-sur-Seine","cp":"94480","departement":"Val-de-Marne (94)","lignes":"RER C","terminus":"Invalides","tmin":25,"tmax":35,"gare":"Oui","lt1h":true,"prixm2":4300,"loyerm2":21},
  {"ville":"Conflans-Sainte-Honorine","cp":"78700","departement":"Yvelines (78)","lignes":"Transilien J","terminus":"Saint-Lazare","tmin":30,"tmax":40,"gare":"Oui","lt1h":true,"prixm2":3300,"loyerm2":18},
  {"ville":"Achères","cp":"78260","departement":"Yvelines (78)","lignes":"RER A / Transilien L","terminus":"Auber / Saint-Lazare","tmin":35,"tmax":45,"gare":"Oui","lt1h":true,"prixm2":3200,"loyerm2":19},
  {"ville":"Poissy","cp":"78300","departement":"Yvelines (78)","lignes":"RER A / Transilien J","terminus":"Auber / Saint-Lazare","tmin":20,"tmax":30,"gare":"Oui","lt1h":true,"prixm2":4100,"loyerm2":22},
  {"ville":"Maisons-Laffitte","cp":"78600","departement":"Yvelines (78)","lignes":"RER A / Transilien L","terminus":"Auber / Saint-Lazare","tmin":20,"tmax":30,"gare":"Oui","lt1h":true,"prixm2":5600,"loyerm2":24},
  {"ville":"Verneuil-sur-Seine","cp":"78480","departement":"Yvelines (78)","lignes":"Transilien J (Eole futur)","terminus":"Saint-Lazare / La Défense (futur)","tmin":35,"tmax":50,"gare":"Oui","lt1h":true,"prixm2":3200,"loyerm2":18},
  {"ville":"Vernouillet","cp":"78540","departement":"Yvelines (78)","lignes":"Transilien J","terminus":"Saint-Lazare","tmin":40,"tmax":55,"gare":"Oui","lt1h":true,"prixm2":2700,"loyerm2":17},
  {"ville":"Les Mureaux","cp":"78130","departement":"Yvelines (78)","lignes":"Transilien J","terminus":"Saint-Lazare","tmin":35,"tmax":50,"gare":"Oui","lt1h":true,"prixm2":2400,"loyerm2":16},
  {"ville":"Cergy","cp":"95000","departement":"Val-d’Oise (95)","lignes":"RER A / Transilien L","terminus":"Auber / Saint-Lazare","tmin":35,"tmax":50,"gare":"Oui","lt1h":true,"prixm2":3200,"loyerm2":18},
  {"ville":"Pontoise","cp":"95300","departement":"Val-d’Oise (95)","lignes":"Transilien J / H / RER C","terminus":"Saint-Lazare / Nord / Invalides","tmin":35,"tmax":50,"gare":"Oui","lt1h":true,"prixm2":3100,"loyerm2":18},
  {"ville":"Champigny-sur-Marne","cp":"94500","departement":"Val-de-Marne (94)","lignes":"RER A (GPE futur)","terminus":"Auber","tmin":20,"tmax":30,"gare":"Oui","lt1h":true,"prixm2":4700,"loyerm2":23},
  {"ville":"Saint-Maur-des-Fossés","cp":"94100","departement":"Val-de-Marne (94)","lignes":"RER A","terminus":"Auber","tmin":20,"tmax":30,"gare":"Oui","lt1h":true,"prixm2":6200,"loyerm2":25},
  {"ville":"Boissy-Saint-Léger","cp":"94470","departement":"Val-de-Marne (94)","lignes":"RER A","terminus":"Auber","tmin":25,"tmax":35,"gare":"Oui","lt1h":true,"prixm2":3900,"loyerm2":21},
  {"ville":"Saint-Cyr-l’École","cp":"78210","departement":"Yvelines (78)","lignes":"RER C / N / U","terminus":"Invalides / Montparnasse / La Défense","tmin":25,"tmax":35,"gare":"Oui","lt1h":true,"prixm2":4200,"loyerm2":21},
  {"ville":"Versailles","cp":"78000","departement":"Yvelines (78)","lignes":"RER C / N / U","terminus":"Invalides / Montparnasse / La Défense","tmin":20,"tmax":30,"gare":"Oui","lt1h":true,"prixm2":6300,"loyerm2":25},
  {"ville":"Massy","cp":"91300","departement":"Essonne (91)","lignes":"RER B / C / TGV","terminus":"Châtelet / Invalides / Montparnasse","tmin":15,"tmax":25,"gare":"Oui","lt1h":true,"prixm2":3700,"loyerm2":20},
  {"ville":"Ris-Orangis","cp":"91130","departement":"Essonne (91)","lignes":"RER D","terminus":"Gare du Nord","tmin":25,"tmax":35,"gare":"Oui","lt1h":true,"prixm2":3000,"loyerm2":18},
  {"ville":"Évry-Courcouronnes","cp":"91000","departement":"Essonne (91)","lignes":"RER D","terminus":"Gare du Nord","tmin":30,"tmax":40,"gare":"Oui","lt1h":true,"prixm2":2800,"loyerm2":17},
  {"ville":"Melun","cp":"77000","departement":"Seine-et-Marne (77)","lignes":"RER D / Transilien R","terminus":"Gare du Nord / Gare de Lyon","tmin":35,"tmax":55,"gare":"Oui","lt1h":true,"prixm2":2900,"loyerm2":17},
  {"ville":"Fontainebleau","cp":"77300","departement":"Seine-et-Marne (77)","lignes":"Transilien R","terminus":"Gare de Lyon","tmin":45,"tmax":60,"gare":"Oui","lt1h":true,"prixm2":4000,"loyerm2":19},
  {"ville":"Mantes-la-Jolie","cp":"78200","departement":"Yvelines (78)","lignes":"Transilien J / N (Eole futur)","terminus":"Saint-Lazare / Montparnasse","tmin":45,"tmax":60,"gare":"Oui","lt1h":true,"prixm2":2500,"loyerm2":16},
  {"ville":"Meulan-en-Yvelines","cp":"78250","departement":"Yvelines (78)","lignes":"Transilien J","terminus":"Saint-Lazare","tmin":40,"tmax":55,"gare":"Oui","lt1h":true,"prixm2":2028,"loyerm2":16},
  {"ville":"Vaux-sur-Seine","cp":"78740","departement":"Yvelines (78)","lignes":"Transilien J","terminus":"Saint-Lazare","tmin":40,"tmax":55,"gare":"Oui","lt1h":true,"prixm2":2800,"loyerm2":17},
  {"ville":"Houilles","cp":"78800","departement":"Yvelines (78)","lignes":"RER A / Transilien J","terminus":"Auber / Saint-Lazare","tmin":15,"tmax":25,"gare":"Oui","lt1h":true,"prixm2":5200,"loyerm2":24},
  {"ville":"Sartrouville","cp":"78500","departement":"Yvelines (78)","lignes":"RER A / Transilien J","terminus":"Auber / Saint-Lazare","tmin":15,"tmax":25,"gare":"Oui","lt1h":true,"prixm2":4500,"loyerm2":22},
  {"ville":"La Frette-sur-Seine","cp":"95530","departement":"Val-d’Oise (95)","lignes":"Transilien J","terminus":"Saint-Lazare","tmin":25,"tmax":35,"gare":"Oui","lt1h":true,"prixm2":3900,"loyerm2":21},
  {"ville":"Herblay-sur-Seine","cp":"95220","departement":"Val-d’Oise (95)","lignes":"Transilien J","terminus":"Saint-Lazare","tmin":25,"tmax":35,"gare":"Oui","lt1h":true,"prixm2":3800,"loyerm2":20},
  {"ville":"Franconville","cp":"95130","departement":"Val-d’Oise (95)","lignes":"RER C / Transilien H","terminus":"Invalides / Nord","tmin":25,"tmax":35,"gare":"Oui","lt1h":true,"prixm2":3700,"loyerm2":20},
  {"ville":"Montigny-lès-Cormeilles","cp":"95370","departement":"Val-d’Oise (95)","lignes":"RER C / Transilien H","terminus":"Invalides / Nord","tmin":25,"tmax":35,"gare":"Oui","lt1h":true,"prixm2":3600,"loyerm2":19},
  {"ville":"Argenteuil","cp":"95100","departement":"Val-d’Oise (95)","lignes":"Transilien J","terminus":"Saint-Lazare","tmin":15,"tmax":25,"gare":"Oui","lt1h":true,"prixm2":4200,"loyerm2":22}
];
